version: '3.8'

services:
  app:
    build: .
    container_name: medea_library_converter
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - MODULE_NAME=main
    restart: unless-stopped
