"""добавил логгер

Revision ID: 4de6e84cc1f1
Revises: 55f8bbbcf01c
Create Date: 2024-10-09 23:18:28.105143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4de6e84cc1f1'
down_revision: Union[str, None] = '55f8bbbcf01c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
