"""добавил булевые поля для автоскана и автоконверта

Revision ID: 55f8bbbcf01c
Revises: a8660ab015db
Create Date: 2024-10-09 16:57:33.878734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55f8bbbcf01c'
down_revision: Union[str, None] = 'a8660ab015db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_path', sa.Column('auto_scan', sa.Boolean(), nullable=True))
    op.add_column('media_path', sa.Column('auto_convert', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'media_path', ['id'])
    op.create_unique_constraint(None, 'settings', ['name'])
    op.create_unique_constraint(None, 'video_path', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'video_path', type_='unique')
    op.drop_constraint(None, 'settings', type_='unique')
    op.drop_constraint(None, 'media_path', type_='unique')
    op.drop_column('media_path', 'auto_convert')
    op.drop_column('media_path', 'auto_scan')
    # ### end Alembic commands ###
