/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-117339-gf25c9cc213-20241004"
#endif /* AVUTIL_FFVERSION_H */
